repos:
  - repo: https://github.com/psf/black
    rev: 23.1a1
    hooks:
      - id: black
        args: [ "." ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [ "-c", "bandit.yaml", "-r", "." ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 6.1.0  # Убедитесь, что используете последнюю версию
    hooks:
      - id: flake8
        additional_dependencies: [ flake8-bugbear ]